#!/bin/bash

# 🚀 Emotion Detection App - Easy Setup Script
# This script helps configure API URL for different environments

echo "🎭 Emotion Detection App Setup"
echo "================================"
echo ""

# Detect OS
OS="$(uname -s)"
case "${OS}" in
    Linux*)     MACHINE=Linux;;
    Darwin*)    MACHINE=Mac;;
    CYGWIN*)    MACHINE=Windows;;
    MINGW*)     MACHINE=Windows;;
    *)          MACHINE="Unknown:${OS}"
esac

echo "🖥️  Detected OS: $MACHINE"
echo ""

# Get IP address based on OS
echo "🔍 Detecting your IP address..."
if [ "$MACHINE" = "Mac" ] || [ "$MACHINE" = "Linux" ]; then
    IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | head -1 | awk '{print $2}')
    echo "📡 Your IP address: $IP"
elif [ "$MACHINE" = "Windows" ]; then
    echo "🪟 On Windows, run: ipconfig | findstr IPv4"
    IP="192.168.1.x"
else
    echo "❓ Please manually find your IP address"
    IP="192.168.1.x"
fi

echo ""
echo "⚙️  Configuration Options:"
echo "1. 📱 Physical Device (Recommended) - Use your IP: $IP"
echo "2. 🤖 Android Emulator - Use: 10.0.2.2"
echo "3. 📱 iOS Simulator - Use: 127.0.0.1"
echo "4. 🌐 Expo Tunnel - Use tunnel URL"
echo ""

read -p "👉 Choose option (1-4): " choice

case $choice in
    1)
        API_URL="http://$IP:8000/api"
        echo "📱 Physical Device selected"
        ;;
    2)
        API_URL="http://10.0.2.2:8000/api"
        echo "🤖 Android Emulator selected"
        ;;
    3)
        API_URL="http://127.0.0.1:8000/api"
        echo "📱 iOS Simulator selected"
        ;;
    4)
        read -p "🔗 Enter your tunnel URL: " TUNNEL_URL
        API_URL="$TUNNEL_URL/api"
        echo "🌐 Tunnel URL selected"
        ;;
    *)
        echo "❌ Invalid option, using localhost"
        API_URL="http://127.0.0.1:8000/api"
        ;;
esac

# Update .env file
echo ""
echo "📝 Updating configuration..."
cat > .env << EOF
# Backend API Configuration - Auto-generated by setup script
# Generated on: $(date)
# Selected: $API_URL

EXPO_PUBLIC_API_BASE_URL=$API_URL

# Other options (uncomment to use):
# EXPO_PUBLIC_API_BASE_URL=http://127.0.0.1:8000/api
# EXPO_PUBLIC_API_BASE_URL=http://10.0.2.2:8000/api
# EXPO_PUBLIC_API_BASE_URL=http://$IP:8000/api
EOF

echo "✅ Configuration saved to .env"
echo "🔗 API URL set to: $API_URL"
echo ""
echo "🚀 Next Steps:"
echo "1. Start backend: cd backend && python app.py"
echo "2. Start frontend: npx expo start --clear"
echo "3. Scan QR code with Expo Go app"
echo ""
echo "🔧 If connection fails, run this script again with different option"